---
- name: Instalar PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Garantir que o PostgreSQL está ativo
  service:
    name: postgresql
    state: started
    enabled: yes